### ISSUE TITLE
[Feature] To-do-list

### ISSUE THREAD

**Issue by ahmadxgani** [ahmadxgani/react-blog-frontend#2]
# Improvement/Refactor And Optimize Code
- [x] Improve UI/UX
- [x] Refactor Tag Component
- [x] Manage image assets (set profile, set article thumbnail, etc), [ref](https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/)
- [ ] only return the needed data in query or mutation, applied in refetch, query, and lazzy query, usecase to fix is in [example of refetch query](https://github.com/SeishinKeiji/simple-blog-frontend/blob/main/src/components/post/DetailPost.tsx) | [ref](https://stackoverflow.com/questions/61616776/apollo-client-possible-to-refetch-only-a-fragment-of-a-larger-query-when-its)
# Users Feature
- [x] Upload Profile Image
- [x] Reset Password
- [x] Forgot Password
- [x] Verify Account After Register 
# WYSWYG
- [x] Upload Image
- [ ] Add Link
# Utitlity Features
- [ ] Add Comment
- [x] Add Bookmark Post feature
- [ ] hide bookmarked post in homepage ( if article > 1000 post :laughing:  ) and show by bookmarked post in profile page
- [x] Add Like Post
- [ ] Save Post As Draft
- [x] Sweetalert As Default Alert
# Fix Bug
- [ ] auto-filled from saved login in register component
- [x] title not changed in page that using parameter in path
- [x] theme-change does not working as well, [ref](https://github.com/saadeghi/theme-change/issues/2)
- [x] protect route path for a user that only can update their own data 
- [ ] [apollo error](https://github.com/apollographql/apollo-client/issues/8677) in log after creating a new post
- [ ] auto-logout if current user not found in database, problem found in localstorage, usecase: user login => admin delete user => and user still have status logged-in
- [ ] issue with [@editorjs/image](https://github.com/editor-js/image/issues/201) `on remove image, delete the image from imgbb => scrape delete url and click delete button? or use expiration date?`
